# Generated by Django 3.2.4 on 2021-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_1',
            field=models.TextField(null=True),
        ),
    ]
