# Generated by Django 3.2.4 on 2021-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Technology/IT', 'Technology/IT'), ('Technology/Electronics', 'Technology/Electronics'), ('Technology/Space', 'Technology/Space'), ('Technology/Others', 'Technology/Others')], default='Technology/Others', max_length=25),
        ),
    ]
