# Generated by Django 3.2.4 on 2021-06-18 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Technology/IT', 'Technology/IT'), ('Technology/Electronics', 'Technology/Electronics'), ('Technology/Space', 'Technology/Space'), ('Technology/Others', 'Technology/Others'), ('Technology/Apps-Softwares', 'Technology/Apps-Softwares')], default='Technology/Others', max_length=25),
        ),
    ]
